//
//  ProgressBarDraw.swift
//  Move
//
//  Created by Lee Palisoc on 2018-11-29.
//  Copyright © 2018 CodeX. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//
//  This code was generated by Trial version of PaintCode, therefore cannot be used for commercial purposes.
//


import UIKit

public class ProgressBarDraw : NSObject {

    //// Drawing Methods

    @objc dynamic public class func drawProgressBar(frame: CGRect = CGRect(x: 0, y: 0, width: 300, height: 15), progress: CGFloat = 193) {
        //// General Declarations
        // This non-generic function dramatically improves compilation times of complex expressions.
        func fastFloor(_ x: CGFloat) -> CGFloat { return floor(x) }

        //// Color Declarations
        let color = UIColor(red: 0.235, green: 0.585, blue: 0.812, alpha: 1.000)
        let color2 = UIColor(red: 0.086, green: 0.390, blue: 0.689, alpha: 1.000)

        //// ProgressBorder Drawing
        let progressBorderPath = UIBezierPath(roundedRect: CGRect(x: frame.minX + 1, y: frame.minY + 1, width: fastFloor((frame.width - 1) * 0.99666 + 0.5), height: 13), cornerRadius: 6.5)
        color.setStroke()
        progressBorderPath.lineWidth = 1
        progressBorderPath.stroke()


        //// ProgressActive Drawing
        let progressActivePath = UIBezierPath(roundedRect: CGRect(x: 1, y: 1, width: progress, height: 13), cornerRadius: 6.5)
        color2.setFill()
        progressActivePath.fill()
    }

}
